### ISSUE TITLE
Cool code!

### ISSUE THREAD

**Issue by 4ndr0666** [CRAWNiiK/GPT-Tab-Fix#2]
Is this just for formatting purposes if chats spits out a script in chunks?

**Comment by CRAWNiiK** [comment]
no, when ChatGPT gives you code, it uses spaces instead of tabs in the code block. 
it looks correct on most text editors but if you were to open it in just regular notepad or use nano on linux, you would be able to see it. 
so this code just takes those 4 spaces and replaces it with an actual indent.
